# -*- coding: utf-8 -*-
"""Untitled11.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1yS0U0yLnAXBpQ8KRRLPo68gouwgT-JKv
"""

import random


personas = []

def validar_rut(rut):
    rut = rut.replace(".", "").replace("-", "")
    if len(rut) != 9 or not rut[:-1].isdigit():
        return False
    multiplicadores = [2, 3, 4, 5, 6, 7, 2, 3]
    total = sum(int(digito) * multiplicador for digito, multiplicador in zip(rut[:-1][::-1], multiplicadores))
    resto = total % 11
    digito_verificador = str(11 - resto)
    if digito_verificador == "11":
        digito_verificador = "0"
    elif digito_verificador == "10":
        digito_verificador = "K"
    return rut[-1].upper() == digito_verificador

def imprimir_personas():
    print("Mostrando Registros:")
    for persona in personas:
        print(f"RUT: {persona['rut']}")
        print(f"Nombre: {persona['nombre']}")
        print(f"Edad: {persona['edad']}")
        print(f"País de nacimiento: {persona['pais_nacimiento']}")
        print(f"Ciudad de nacimiento: {persona['ciudad_nacimiento']}")
        print("-----------------------------------------------------")

def grabar_persona():
    rut = input("Ingrese el RUT de la persona : ")
    while not validar_rut(rut):
        print("RUT inválido. Por favor, ingréselo nuevamente.")
        rut = input("Ingrese el RUT de la persona: ")

    nombre = input("Ingrese el nombre de la persona: ")
    while len(nombre) < 8:
        print("Formato Nombre Apellido.")
        nombre = input("Ingrese el nombre de la persona: ")

    edad = int(input("Ingrese la edad de la persona: "))
    while edad < 0:
        print("La edad debe ser mayor o igual a 0.")
        edad = int(input("Ingrese la edad de la persona: "))

    pais_nacimiento = input("Ingrese el país de nacimiento de la persona: ")
    ciudad_nacimiento = input("Ingrese la ciudad de nacimiento de la persona: ")
    estado_conyugal = input("ingrese el estado conyugal de la persona:")

    persona = {
        "rut": rut,
        "nombre": nombre,
        "edad": edad,
        "pais_nacimiento": pais_nacimiento,
        "ciudad_nacimiento": ciudad_nacimiento,
        "estado_conyugal": estado_conyugal
    }

    personas.append(persona)
    print("Datos de la persona grabados correctamente.")

def buscar_persona():
    rut = input("Ingrese el RUT de la persona a buscar: ")
    for persona in personas:
        if persona["rut"] == rut:
            print("Información de la persona:")
            print(f"RUT: {persona['rut']}")
            print(f"Nombre: {persona['nombre']}")
            print(f"Edad: {persona['edad']}")
            print(f"País de nacimiento: {persona['pais_nacimiento']}")
            print(f"Ciudad de nacimiento: {persona['ciudad_nacimiento']}")
            print(f"Estado conyugal: {persona['estado_conyugal']}")
            if persona['pais_nacimiento'].lower() == 'Argentina':
                print("La persona Es Argentina")
            return

    print("No se encontró ninguna persona con ese RUT.")


def imprimir_certificados():
    certificados = [
        {
            "nombre": "Certificado de Nacimiento",
            "codigo": "CN"
        },
        {
            "nombre": "Estado Conyugal",
            "codigo": "EC"
        },
        {
            "nombre": "Pertenece a argentina",
            "codigo": "PC"
        }
    ]

    for certificado in certificados:
        print(f"Nombre del certificado: {certificado['nombre']}")
        rut = input("Ingrese el RUT de la persona: ")
        for persona in personas:
            if persona["rut"] == rut:
                print(f"RUT de la persona: {persona['rut']}")
                print(f"Nombre de la persona: {persona['nombre']}")
                print(f"Edad de la persona: {persona['edad']}")
                print(f"estado conyugal de la persona: {persona['estado_conyugal']}")
                print(f"Datos adicionales del certificado {certificado['codigo']}")

def eliminar_persona():
    rut = input("Ingrese el RUT de la persona a eliminar: ")
    for persona in personas:
        if persona["rut"] == rut:
            personas.remove(persona)
            print("La persona ha sido eliminada correctamente.")
            return

    print("No se encontró ninguna persona con ese RUT.")

def imprimir_menu():
    print("\n------ MENÚ ------")
    print("1. Grabar")
    print("2. Buscar")
    print("3. Imprimir certificados")
    print("4. Eliminar")
    print("5 mostrar personas guardadas")
    print("6. Salir")

def main():
    print("Bienvenido al programa de RENAPER de autoservicio de atención rápida")
    print("Versión 1.0\n")

    while True:
        imprimir_menu()
        opcion = input("Ingrese el número de la opción que desea seleccionar: ")

        if opcion == "1":
            grabar_persona()
        elif opcion == "2":
            buscar_persona()
        elif opcion == "3":
            imprimir_certificados()
        elif opcion == "4":
            eliminar_persona()
        elif opcion == "5":
            imprimir_personas()
        elif opcion == "6":
            print("Gracias por utilizar el programa de RENAPER . chekuna jeudy version 1.0")
            break
        else:
            print("Opción inválida. Por favor, ingrese una opción válida.")

if __name__ == "__main__":
    main()